# Generated by Django 5.0.6 on 2024-07-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='staus',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='staus',
        ),
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.CharField(default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
