# Generated by Django 5.0.6 on 2024-07-07 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_donation_donationname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='adminremark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donationarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.donationarea'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='updationdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.volunteer'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='volunteerremark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
